[package]
name = "task-supervisor"
version = "0.3.3"
edition = "2021"
rust-version = "1.81"
categories = ["asynchronous"]
description = "Tokio tasks Supervisor"
authors = ["akhercha <adel@pragma.build>"]
keywords = ["tasks", "tokio", "supervisor"]
repository = "https://github.com/akhercha/task-supervisor"
license = "MIT"

[features]
with_tracing = ["dep:tracing"]

[dependencies]
tokio = { version = "^1.43.0", features = ["full", "test-util"] }
tokio-util = "0.7.13"
async-trait = "0.1.87"
futures = { version = "0.3.31", features = ["compat"] }
thiserror = "2.0.12"
anyhow = "1"

tracing = { version = "0.1", optional = true }
